### ISSUE TITLE
request to update pre-built windows dll

### ISSUE THREAD

**Issue by jip** [jsoftware/math_lapack2#7]
To continue a discussion in JForum: [1].

Pre-built DLLs for lapack2 addon are located on Jsoftware site [2]:
| filename | datetime | size |
| --- | --- | ---: |
| [liblapack3.dll](https://www.jsoftware.com/download/lapackbin/liblapack3.dll) | 2019-01-01 11:15 | 5181440 |
| [liblapack3_32.dll](https://www.jsoftware.com/download/lapackbin/liblapack3_32.dll) | 2019-01-01 11:15 | 4447744 |

Both export 1434 definitions. To compare, the number of definitions for some LAPACK versions:

| LAPACK version | exported definitions |
| :--- | ---: |
| 3.0 | 1301 |
| 3.1 | 1365 |
| 3.1.1 | 1363 |
| 3.2.2 | 1475 |
| 3.3.1 | 1515 |
| 3.4.0 | 1547 |
| 3.5.0 | 1621 |
| 3.7.0 | 1827 |
| 3.9.0 | 1869 |
| 3.10.0 | 1899 |
| 3.11.0 | 1913 |
| 3.12.0 (current) | 1935 |

`liblapack3.dll` looks like a patched 3.0 version.

Pros:
- it misses `ilaver_` introduced in version 3.1
- it misses `dlansf_` introduced in version 3.2
- it contains `dlarfp_` which was renamed to `dlarfgp_` since version 3.2.2
- it misses `dbbcsd_`,`dorcsd_` introduced in version 3.3

Cons:
- it contains `dlaqr0_`,`dlahr2_` introduced in version 3.1
- it contains `dptttf_`,`dlansf_`,`dgejsv_` introduced in version 3.2

As noted in thread [1], there are LAPACK 3.7.0 pre-built DLLs for Windows both 32-bit and 64-bit [3]. So I propose to update content of [2] by DLLs from [3].

References:
1. https://www.jsoftware.com/pipermail/general/2023-April/039684.html or https://groups.google.com/a/jsoftware.com/g/forum/c/JFj2sHHGY9Y/m/Aj920imzAQAJ
2. http://www.jsoftware.com/download/lapackbin/
3. https://icl.utk.edu/lapack-for-windows/lapack/

**Comment by bilam** [comment]
Does [3]
1. integrates optimized blas
2. Zero external dll dependencies

**Comment by jip** [comment]
1. I guess no. It exports BLAS names. If it was built by standard Makefile, then it integrates a reference (non-optimized) BLAS.
2.  No:
```console
> strings liblapack.dll | fgrep .dll
libgcj-16.dll
liblapack.dll
libblas.dll
KERNEL32.dll
msvcrt.dll
libgcc_s_seh_64-1.dll
libgfortran_64-3.dll
```

An OpenBLAS alternative https://github.com/OpenMathLib/OpenBLAS may be used instead to fulfill this requirements:
1. It integrates optimized BLAS.
2. It has the minimum external DLL dependencies:
```console
> strings libopenblas.dll | fgrep .dll
libopenblas.dll
KERNEL32.dll
msvcrt.dll
```
It replaces LAPACK library transparently.

See Release section, DLL files are packed into `OpenBLAS-0.3.26-x64.zip` and `OpenBLAS-0.3.26-x86.zip`.

**Comment by bilam** [comment]
The openblas alternative looks good. May I know it's lapack version?  Is it
newer than our current version?
Can you run some rudimentary test?
Thanks.

**Comment by jip** [comment]
OpenBLAS 0.3.26 incorporates LAPACK 3.12.0 . Which is newer than patched LAPACK 3.0 in liblapack.dll for lapack2 addon on Jsoftware site.

Running tests revealed an error appeared in J9 since J807. I've pushed the fix in the same PR #6. Now tests are passed ok. Tested with reference LAPACK and OpenBLAS libraries.

**Comment by bilam** [comment]
PR merged. Thanks

I will update the windows binary later.

**Comment by bilam** [comment]
I have updated the windows binaries on jsoftware server download folder.

**Comment by bilam** [comment]
But I can't understand why the binary size is nearly 10x as the old binary.
